# Generated by Django 3.1 on 2020-08-14 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo_codes', '0002_auto_20200813_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedpromocode',
            name='company',
            field=models.CharField(blank=True, default='None', help_text='Name of the business Company', max_length=64, unique=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='typeOfPayment',
            field=models.CharField(choices=[('cash', 'cash'), ('visa', 'visa')], default='Cash', help_text='Cash or Visa', max_length=16, verbose_name='Type of payment'),
        ),
        migrations.AlterField(
            model_name='claimedpromocode',
            name='redeemed',
            field=models.DateTimeField(auto_now_add=True, help_text='Which User is it bounded to?', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bound',
            field=models.BooleanField(default=False, help_text='Is this coupon bound to a specific user?', verbose_name='Bound to user'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='The unique promo code', max_length=64, verbose_name='Promo Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_l',
            field=models.CharField(blank=True, help_text='Lower Case Promo Code to have unique codes', max_length=64, unique=True, verbose_name='Lower Case Promo Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expires',
            field=models.DateTimeField(blank=True, help_text='When it expires (if it expires)', null=True, verbose_name='Expire Time'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='repeat',
            field=models.IntegerField(default=0, help_text="How many times this coupon can be used, 0 == infinitely, otherwise it's a number, such as 1 or many.", verbose_name='Repeat'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value')], help_text='Percentage or a value.', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Which User is it bounded to?', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="If percentage based make sure it's no greater than 1.0", max_digits=10, verbose_name='Promo Code Value'),
        ),
    ]
