# Generated by Django 3.1 on 2020-08-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0003_auto_20200814_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedpromocode',
            name='typeOfPayment',
            field=models.CharField(choices=[('cash', 'cash'), ('visa', 'visa'), ('ewallet', 'ewallet')], default='Cash', help_text='Cash or Visa', max_length=16, verbose_name='Type of payment'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bound',
            field=models.BooleanField(default=False, help_text='Is this Promo Code bound to a specific user?', verbose_name='Bound to user'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='repeat',
            field=models.IntegerField(default=0, help_text="How many times this Promo Code can be used, 0 == infinitely, otherwise it's a number, such as 1 or many.", verbose_name='Repeat'),
        ),
    ]
