# Generated by Django 3.1 on 2020-08-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0004_auto_20200814_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedpromocode',
            name='item',
            field=models.CharField(blank=True, default='None', help_text='What type of item', max_length=64, unique=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='service',
            field=models.CharField(blank=True, default='None', help_text='Name of the service', max_length=64, unique=True, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='How much did the user [ay', max_digits=10, verbose_name='Total Price'),
        ),
    ]
