# Generated by Django 3.1 on 2020-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0006_auto_20200814_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedpromocode',
            name='company',
            field=models.CharField(default='', help_text='Name of the business Company', max_length=64, unique=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='item',
            field=models.CharField(default='', help_text='What type of item', max_length=64, unique=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='service',
            field=models.CharField(default='', help_text='Name of the service', max_length=64, unique=True, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='How much did the user pay', max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='claimedpromocode',
            name='typeOfPayment',
            field=models.CharField(choices=[('cash', 'cash'), ('visa', 'visa'), ('ewallet', 'ewallet')], default='Cash', help_text='Cash or Visa', max_length=16, verbose_name='Type of payment'),
        ),
        migrations.AlterField(
            model_name='claimedpromocode',
            name='redeemed',
            field=models.DateTimeField(auto_now_add=True, help_text='Redeem Time', verbose_name='Redeem'),
        ),
    ]
