# Generated by Django 3.1 on 2020-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0007_auto_20200814_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedpromocode',
            name='company',
            field=models.CharField(default='', help_text='Name of the business Company', max_length=64, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='claimedpromocode',
            name='item',
            field=models.CharField(default='', help_text='What type of item', max_length=64, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='claimedpromocode',
            name='service',
            field=models.CharField(default='', help_text='Name of the service', max_length=64, verbose_name='Service'),
        ),
    ]
